Web.MVC/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.MVC.Models
{
    public class Cart
    {
        public Cart()
        {

        }
        public Cart(string  userName)
        {
            this.Id = Guid.NewGuid();
            this.UserName = userName;
            this.Order = new Order();
        }
        public Guid Id { get; set; }
        public string UserName { get; set; }
        public Order Order { get; set; }
    }
}

Web.MVC/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Web.MVC.Models;

namespace Web.MVC.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IOrdersService ordersService;

        public OrderPageViewModel viewModel = new OrderPageViewModel();

        public CartController(IOrdersService _ordersService)
        {
            ordersService = _ordersService;
        }
        // GET: Order
        public IActionResult Index(string message)
        {
            ViewBag.Message = message;
            this.viewModel.Cart = ordersService.GetCart(User.Identity.Name);
            this.viewModel.PastOrders = ordersService.GetOrderHistory(User.Identity.Name);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult PlaceOrder()
        {
            ordersService.PlaceOrder(User.Identity.Name);
            return RedirectToAction("Index", new { message = "Order Placed Successfully!" });
        }

        public IActionResult Delete(Guid id)
        {
            this.ordersService.RemoveItem(User.Identity.Name, id);
            return RedirectToAction("Index",  new { message = "Item Removed!" });
        }
    }
}

Web.MVC/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Web.MVC.Models;

namespace Web.MVC.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrdersService ordersService;

        public OrderPageViewModel viewModel = new OrderPageViewModel();

        public OrderController(IOrdersService _ordersService)
        {
            ordersService = _ordersService;
        }
        // GET: Order
        public IActionResult Index()
        {
            this.viewModel.PastOrders = ordersService.GetOrderHistory(User.Identity.Name);
            return View("List", viewModel);
        }

        public IActionResult Details(Guid  id)
        {
            this.viewModel.Cart = ordersService.getOrder(User.Identity.Name, id);
            return View(this.viewModel);
        }
    }
}

Web.MVC/Views/Cart/Index.cshtml
@model OrderPageViewModel
@{
    ViewData["Title"] = "Shopping Cart";
}
<div class="text-center">
    <img src="~/img/logo_big.jpg" />
</div>
<h3 class="alert-success">@ViewBag.Message</h3>
<h2>
    Shopping Cart
    <a class="btn btn-lg btn-primary" style="float:right; margin-bottom: 10px;" asp-controller="Home" asp-action="Index"> Countinue Shoping </a>
</h2>
@if (Model.Cart.Order.Products.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>Item</th>
                <th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cart.Order.Products)
            {
                <tr>
                    <td>
                        <div>
                            <img width="100" style="float:left" src="@item.Image" />
                            <b>@item.Name</b>: <span> @item.Description</span>
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SalesPrice)
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-id="@item.Id">Remove</a>
                    </td>
                </tr>
            }
            <tr>
                <td>
                    Total Items: @Model.Cart.Order.TotalItems
                </td>
                <td>
                    @Model.Cart.Order.TotalPrice
                </td>
                <td>
                    <form asp-action="PlaceOrder" method="post">
                        <button class="btn btn-primary"> Place Order </button>
                    </form>
                </td>
            </tr>
        </tbody>
    </table>
    <hr />
}
else
{
    <span>
        Your cart is empty!
    </span>
}
<br />
<br />
@if (Model.PastOrders.Any())
{
<div class="text-center">
    <a asp-controller="Order" asp-action="Index">View Past Order</a>
</div>
}